### ISSUE TITLE
QA 30087: KeyError: 'oauth_state'

### ISSUE THREAD

**Issue by joshmoore** [manics/omero-oauth#1]
Info:

 * Web Bug 5.8.1
 * Python 3.6

Sent from web 5.8.1 (running on AWS with Python 3.6.8):

```
Traceback (most recent call last):

File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
response = get_response(request)

File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
response = self.process_exception_by_middleware(e, request)

File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/views/generic/base.py", line 68, in view
return self.dispatch(request, *args, **kwargs)

File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
return bound_func(*args, **kwargs)

File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
return view(request, *args, **kwargs)

File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
return func.__get__(self, type(self))(*args2, **kwargs2)

File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/webgateway/views.py", line 3098, in dispatch
return super(LoginView, self).dispatch(*args, **kwargs)

File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
return handler(request, *args, **kwargs)

File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero_oauth-0.0.2-py3.6.egg/omero_oauth/views.py", line 81, in get
state = request.session.pop('oauth_state')

File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 73, in pop
return self._session.pop(key, *args)

KeyError: 'oauth_state'
```

**Comment by jburel** [comment]
See also https://www.openmicroscopy.org/qa2/qa/feedback/31177/
Web: 5.13.0
Python 3.6

**Comment by manics** [comment]
This usually indicates the oauth process wasn't followed properly, e.g. someone clicking refresh at the wrong time, or going straight to an intermediate page instead of via a redirect.

**Comment by dominikl** [comment]
Another one: [QA 31184](https://www.openmicroscopy.org/qa2/qa/feedback/31184/)
